"""initial

Revision ID: 454168c3cf3e
Revises: 
Create Date: 2022-11-27 17:09:31.794722

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "454168c3cf3e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("task", "subject", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_task_uuid"), "task", ["uuid"], unique=False)
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_user_uuid"), "user", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_uuid"), table_name="user")
    op.alter_column("user", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_task_uuid"), table_name="task")
    op.alter_column("task", "subject", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
